build:
  image: pdxjohnny/ant
  commands:
    - bash scripts/build.sh
publish:
  github_release:
    api_key: "$$GITHUB_API_KEY"
    files:
      - out/artifacts/Web/Web.jar
      - out/artifacts/Database/Database.jar
      - out/artifacts/Tests/Tests.jar
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
notify:
  email:
    from: "$$EMAIL_USERNAME"
    host: smtp.gmail.com
    username: "$$EMAIL_USERNAME"
    password: "$$EMAIL_PASSWORD"
    recipients:
      - "$$EMAIL_TO"
  irc:
    prefix: build
    recipient: pdxjohnny
    nick: "$$IRC_NICK"
    channel: "$$IRC_CHAN"
    server:
      host: chat.freenode.net
      port: 6697
      tls: true
